baseImage: "python:3.11-slim"
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

packages: "numpy,pandas"

service:
  port: 5000
  targetPort: 5000
  type: ClusterIP

hpa:
  name: python-dev-environment-hpa
  namespace: default  # or any other namespace you want
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 20  # Scale down when CPU usage goes below 20%
  memoryUtilization: 60  # Scale down when memory usage goes below 60%

resourceQuota:
  teamA:
    requests:
      cpu: "4"
      memory: "8Gi"
    limits:
      cpu: "8"
      memory: "16Gi"
    pods: "8"
  
  teamB:
    requests:
      cpu: "4"
      memory: "8Gi"
    limits:
      cpu: "8"
      memory: "16Gi"
    pods: "8"

externalDNS:
  provider: aws
  aws:
    region: us-west-2
  sources:
    - service
    - ingress
  domainFilters:
    - domainname.com
