apiVersion: v1
kind: Service
metadata:
  name: python-dev-environment
spec:
  selector:
    app: python-dev-environment
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: my-service.domainname.com
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: my-app
